config/routes.rb
Rails.application.routes.draw do
  get 'pets', to: 'pets#index'
  get 'pets/new', to: 'pets#new', as: :new_pet
  get 'pets/:id', to: 'pets#show', as: :pet
  post 'pets', to: 'pets#create'
  get 'pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch 'pets/:id', to: 'pets#update'
  delete 'pets/:id', to: 'pets#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat rabbit bird turtle)
  validates :name, presence: true
  validates :species, inclusion: { in: %w(dog cat rabbit bird turtle) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # We find the pet in our Database with Active Record find method
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pets_path
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :species, :address, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostKitty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/pets/edit.html.erb
<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<h1>List of found pets</h1>

<% @pets.each do |pet| %>
  <h3><%= link_to pet.name, pet_path(pet)  %></h3>
  <ul>
    <li>Found on: <%= pet.found_on %></li>
    <li>Species: <%= pet.species  %></li>
    <li>Address: <%= pet.address  %></li>
  </ul>
<% end %>

<p><%= link_to 'Add a pet you found', new_pet_path %></p>

app/views/pets/new.html.erb
<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1>Name: <%= @pet.name %> - Species: <%= @pet.species  %></h1>

<h3>Address: <%= @pet.address %></h3>
<p>Found on: <%= @pet.found_on %></p>

<%= link_to 'Find more pets!', pets_path %>

<%= link_to 'Delete this pet?', pet_path(@pet), method: :delete  %>